apiVersion: v1
kind: Pod
metadata:
  name: client-prod
  labels:
    component: web
spec:
  container:
    - name: client
    - image: ngquangan/fib-calculator-client
    - ports:
      - containerPort: 3000